# Generated by Django 4.1.1 on 2022-09-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='departed',
            field=models.BooleanField(default=False),
        ),
    ]
